#######################################################################################
# A default configuration that will be loaded for all jupyter books
# Users are expected to override these values in their own `_config.yml` file.
# This is also the "master list" of all allowed keys and values.

#######################################################################################
# Book settings
title                       :  # The title of the book. Will be placed in the left navbar.
author                      : Anukool Chaturvedi
email                       : chaturvedianukool@gmail.com # The author of the book
copyright                   : "2024"  # Copyright year to be placed in the footer
logo                        : "assets/images/MLGuide_logo_nb.png"
# Patterns to skip when building the book. Can be glob-style (e.g. "*skip.ipynb")
exclude_patterns            : [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]
# Auto-exclude files not in the toc
only_build_toc_files        : false

#######################################################################################
# Execution settings
execute:
  execute_notebooks         : "off"  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""    # A path to the jupyter cache that will be used to store execution artifacts. Defaults to `_build/.jupyter_cache/`
  exclude_patterns          : []    # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)
  timeout                   : 500    # The maximum time (in seconds) each notebook cell is allowed to run.
  run_in_temp               : true # If `True`, then a temporary directory will be created and used as the command working directory (cwd),
                                    # otherwise the notebook's parent directory will be the cwd.
  allow_errors              : true # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.
  stderr_output             : show  # One of 'show', 'remove', 'remove-warn', 'warn', 'error', 'severe'

#######################################################################################
# Parse and render settings
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist
    - colon_fence
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true  # Allow display math ($$) within an inline context

#######################################################################################
# HTML-specific settings
html:
  favicon                   : "assets/images/logo.png"  # A path to a favicon image
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : false  # Whether to add a link to your repository button
  use_issues_button         : false  # Whether to add an "open an issue" button
  use_multitoc_numbering    : false   # Continuous numbering across parts/chapters
  google_analytics_id       : "G-GJG3T4ZRZH"  # A GA id that can be used to track book views.
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar
  baseurl                   : "https://mlguide.in/"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  comments:
    hypothesis              : false
    utterances              : false
  announcement              : "" # A banner announcement at the top of the site.
html_context:
  default_mode: light

#######################################################################################
# LaTeX-specific settings
latex:
  latex_engine              : pdflatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  use_jupyterbook_latex     : true # use sphinx-jupyterbook-latex for pdf builds as default

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : "jupyterlab"  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  # jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                     : true  # Add a thebe button to pages (requires the repository to run on Binder)
  colab_url                 : https://colab.research.google.com
#  The URL of Google Colab (https://colab.research.google.com)

repository:
  url                       : https://github.com/anukchat/mlguide # The URL to your book's repository
  path_to_book              : "" # A path to your book's folder, relative to the repository root.
  branch                    : main  # Which branch of the repository should be used when creating links

#######################################################################################
# Advanced and power-user settings

sphinx:
  extra_extensions:
    - sphinx_togglebutton
    - sphinx_copybutton
    - myst_nb
    - jupyter_book
    - sphinx_comments
    - sphinx_external_toc
    - sphinx.ext.intersphinx
    - sphinx_design
    - sphinx_jupyterbook_latex
    - ablog

  config:
    html_theme: sphinx_book_theme
    html_extra_path: ['assets']
    html_show_copyright: false
    html_css_files: ['custom.css']
    html_js_files:
      - subscription_overlay.js
      - https://apis.google.com/js/platform.js
    html_head_extra: |
      <meta name="google-signin-client_id" content="415025588210-l56g7pger5g8914op033ukl17f16i5m6.apps.googleusercontent.com">
    blog_path: content/resources/blogs
    disqus_shortname: mlguide
    blog_baseurl: https://mlguide.in
    post_auto_excerpt_length: 50
    html_theme_options:
      secondary_sidebar_items:
        "**":
          - page-toc
        content/resources/blogs/*/*:
          - ablog/recentposts.html
          - ablog/categories.html
          - ablog/tagcloud.html
      extra_footer: |
        <div class="social-icons">
            <a href="https://twitter.com/chaturanukool" target="_blank"><i class="fab fa-twitter"></i></a>
            <a href="https://linkedin.com/in/anukool-chaturvedi" target="_blank"><i class="fab fa-linkedin"></i></a>
            <a href="https://github.com/anukchat" target="_blank"><i class="fab fa-github"></i></a>
            </p>
        </div>
        