###############################################################################
# Auto-generated by `jupyter-book config`
# If you wish to continue using _config.yml, make edits to that file and
# re-generate this one.
###############################################################################
author = 'Anukool Chaturvedi'
blog_baseurl = 'https://mlguide.in'
blog_path = 'content/resources/blogs'
comments_config = {'hypothesis': False, 'utterances': False}
copyright = '2024'
disqus_shortname = 'mlguide'
exclude_patterns = ['**.ipynb_checkpoints', '.DS_Store', 'Thumbs.db', '_build']
extensions = ['sphinx_togglebutton', 'sphinx_copybutton', 'myst_nb', 'jupyter_book', 'sphinx_thebe', 'sphinx_comments', 'sphinx_external_toc', 'sphinx.ext.intersphinx', 'sphinx_design', 'sphinx_book_theme', 'sphinx_jupyterbook_latex', 'ablog', 'sphinx_jupyterbook_latex']
external_toc_exclude_missing = False
external_toc_path = '_toc.yml'
html_baseurl = 'https://mlguide.in/'
html_css_files = ['intro.css', 'custom.css']
html_extra_path = ['assets']
html_favicon = 'assets/images/logo.png'
html_js_files = ['subscription_overlay.js', 'landing.js']
html_logo = 'assets/images/MLGuide_logo_nb.png'
html_show_copyright = False
html_sourcelink_suffix = ''
html_static_path = ['_static']
html_theme = 'sphinx_book_theme'
html_theme_options = {'secondary_sidebar_items': {'**': ['page-toc'], 'content/resources/blogs/*/*': ['ablog/recentposts.html', 'ablog/categories.html', 'ablog/tagcloud.html']}, 'launch_buttons': {'notebook_interface': 'jupyterlab', 'binderhub_url': 'https://mybinder.org', 'jupyterhub_url': '', 'thebe': True, 'colab_url': 'https://colab.research.google.com'}, 'repository_url': 'https://github.com/anukchat/mlguide', 'path_to_docs': '', 'repository_branch': 'main', 'extra_footer': '<div class="social-icons">\n    <a href="https://twitter.com/chaturanukool" target="_blank"><i class="fab fa-twitter"></i></a>\n    <a href="https://linkedin.com/in/anukool-chaturvedi" target="_blank"><i class="fab fa-linkedin"></i></a>\n    <a href="https://github.com/anukchat" target="_blank"><i class="fab fa-github"></i></a>\n    </p>\n</div>\n', 'analytics': {'google_analytics_id': 'G-GJG3T4ZRZH'}}
html_title = ''
latex_engine = 'pdflatex'
myst_enable_extensions = ['amsmath', 'dollarmath', 'html_admonition', 'html_image', 'linkify', 'replacements', 'smartquotes', 'substitution', 'tasklist', 'colon_fence']
myst_url_schemes = ['mailto', 'http', 'https']
nb_execution_allow_errors = True
nb_execution_cache_path = ''
nb_execution_excludepatterns = []
nb_execution_in_temp = True
nb_execution_mode = 'off'
nb_execution_timeout = 500
nb_output_stderr = 'show'
numfig = True
pygments_style = 'sphinx'
suppress_warnings = ['myst.domains']
use_jupyterbook_latex = True
use_multitoc_numbering = False
