name: deploy-book

# Only run this when the main branch changes
on:
  push:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - name: code checkout
      uses: actions/checkout@v4.1.1

    # Install dependencies
    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.10.13
    - name: Install dependencies
      run: |
        pip install -r requirements_book.txt --no-cache-dir

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build . --all
        
    # copy artifacts
    - name: copy artifacts
      run: |
        cp -r "./content/essentials/python/introduction/img" "_build/html/content/essentials/python/introduction/img"
        cp -r "./content/essentials/python/controlflow/img" "_build/html/content/essentials/python/controlflow/img"
        cp -r "./content/essentials/python/functions/img" "_build/html/content/essentials/python/functions/img"
        cp -r "./content/essentials/python/files/img" "_build/html/content/essentials/python/files/img"
        cp -r "./content/essentials/python/objects/img" "_build/html/content/essentials/python/objects/img"
        cp -r "./content/essentials/python/advanced/img" "_build/html/content/essentials/python/advanced/img"
        cp -r "./content/essentials/python/datetime/img" "_build/html/content/essentials/python/datetime/img"
        cp -r "./content/tools/numpy/img" "_build/html/content/tools/numpy/img"
        cp  ./content/tools/numpy/*.txt "_build/html/content/tools/numpy/"
        cp  ./content/tools/numpy/*.pdf "_build/html/content/tools/numpy/"
        cp -r "./content/tools/numpy/Data_Analysis_with_NumPy" "_build/html/content/tools/numpy/Data_Analysis_with_NumPy"
        cp -r "./content/tools/pandas/img" "_build/html/content/tools/pandas/img"
        cp -r "./content/tools/pandas/001_Python_Pandas_Methods/img" "_build/html/content/tools/pandas/001_Python_Pandas_Methods/img"
        cp ./content/tools/pandas/*.pdf "_build/html/content/tools/pandas/"
        cp ./content/tools/pandas/*.csv "_build/html/content/tools/pandas/"
        cp ./content/tools/pandas/001_Python_Pandas_Methods/*.csv "_build/html/content/tools/pandas/001_Python_Pandas_Methods/"


        

    # Push the book's HTML to github-pages./docs/_myfolder/${foldername}.md
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
