name: deploy-book

# Only run this when the main branch changes
on:
  push:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - name: code checkout
      uses: actions/checkout@v4.1.1

    # Install dependencies
    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.10.13
    - name: Install dependencies
      run: |
        pip install -r requirements_book.txt --no-cache-dir

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build . --all
        
    # copy artifacts
    - name: copy artifacts
      run: |
        cp  ./content/ai/*.png "_build/html/content/ai/"
        cp  ./content/ai/classicml/concepts/*.csv "_build/html/content/ai/classicml/concepts/"
        cp  ./content/ai/classicml/concepts/*.txt "_build/html/content/ai/classicml/concepts/"
        cp  -r ./content/ai/classicml/concepts/machine_learning_andrewng "_build/html/content/ai/classicml/concepts/machine_learning_andrewng/"
        cp  -r ./content/ai/classicml/concepts/machine_learning_lazy "_build/html/content/ai/classicml/concepts/machine_learning_lazy/"
        cp  -r ./content/ai/classicml/images "_build/html/content/ai/classicml/images/"
        cp  -r ./content/ai/neural/concepts/images "_build/html/content/ai/neural/concepts/images/"
        cp  ./content/ai/neural/concepts/*.csv "_build/html/content/ai/neural/concepts/"
        cp  -r ./content/ai/neural/concepts/pytorch/images "_build/html/content/ai/neural/concepts/pytorch/images/"
        cp  ./content/ai/neural/concepts/pytorch/*.py "_build/html/content/ai/neural/concepts/pytorch/"
        cp  -r ./content/ai/neural/concepts/machine_learning_andrewng "_build/html/content/ai/neural/concepts/machine_learning_andrewng/"
        cp  -r ./content/analytics/matplotlib/images "_build/html/content/analytics/matplotlib/images/"
        cp  ./content/analytics/matplotlib/*.csv "_build/html/content/analytics/matplotlib/"
        cp  ./content/analytics/matplotlib/*.png "_build/html/content/analytics/matplotlib/"
        cp  ./content/analytics/matplotlib/*.pdf "_build/html/content/analytics/matplotlib/"
        cp  -r ./content/analytics/numpy/images "_build/html/content/analytics/numpy/images/"
        cp  -r ./content/analytics/numpy/Data_Analysis_with_NumPy "_build/html/content/analytics/numpy/Data_Analysis_with_NumPy/"
        cp  -r ./content/analytics/pandas/images "_build/html/content/analytics/pandas/images/"
        cp  -r ./content/analytics/pandas/dataset "_build/html/content/analytics/pandas/dataset/"
        cp  -r ./content/genai/concepts/transformers/images "_build/html/content/genai/concepts/transformers/images/"
        cp  ./content/genai/langchain/*.zip "_build/html/content/genai/langchain/"
        cp  -r ./content/mathematics/sourceimages "_build/html/content/mathematics/sourceimages/"
        cp  ./content/mathematics/*.py "_build/html/content/mathematics/"
        cp  -r ./content/python/images "_build/html/content/python/images/"
        cp  ./content/python/*.png "_build/html/content/python/"
        cp  ./content/python/*.json "_build/html/content/python/"
        cp  ./content/python/*.txt "_build/html/content/python/"

        

    # Push the book's HTML to github-pages./docs/_myfolder/${foldername}.md
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
